// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeghvmszrfomcmyhsnkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lZ2h2bXN6cmZvbWNteWhzbmtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExODI3NzMsImV4cCI6MjA3Njc1ODc3M30.WhRXMkIVSXDZbcR-6bmNTwM9EcliXgTIXA100QhvdDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);