// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmyyrcmeiaokzlhgtabp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRteXlyY21laWFva3psaGd0YWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzI2MDcsImV4cCI6MjA2NTA0ODYwN30.jmzdx-bFohvlV-EiMCWgw_p0mngJQ9DON8S4PW2H2o8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);